defaultMarkdownHandler = "goldmark"

[goldmark.parser.attribute]
    block = true

[goldmark.renderer]
    unsafe = true

[highlight]
    codeFences         = false
    guessSyntax        = true
    hl_Lines           = ""
    lineNoStart        = 1
    lineNos            = false
    lineNumbersInTable = true
    noClasses          = true
    style              = "dracula"
    tabWidth           = 2
