archived_version       = false
childPageSummaryLength = 100     # Number of characters to show in child summary
homePage               = "/docs" # If removed, the site will have a landing page
noPageIndex            = false   # Turns off child page index
no_list                = true    # Don't show index if there are no children
show_metalinks         = true

time_format_blog    = "Monday, January 02, 2006"
time_format_default = "January 2, 2006"

offlineSearch              = true
offlineSearchMaxResults    = 10
offlineSearchSummaryLength = 70

airgapped = false # Set to true to remove CDN dependencies

# [reveal_hugo]
#   history = true

#   [reveal_hugo.templates.grey]
#     background = "#424242"
#     transition = "convex"

[drawio]
  enable = false

[plantuml]
  enable = false

[print]
  disable_toc = false

[markmap]
  enable = true

[mermaid]
  enable = true
  theme  = "dark"

  [mermaid.flowchart]
    diagramPadding = 20

[ui]
  breadcrumb_disable    = false
  sidebar_cache_limit   = 10
  sidebar_menu_compact  = true
  sidebar_menu_foldable = true

  [ui.readingtime]
    enable = true
