homePage                   = "/docs"                    # If this is removed then then the site will show a landing page.
offlineSearch              = true
offlineSearchMaxResults    = 10
offlineSearchSummaryLength = 70
show_metalinks             = false
time_format_blog           = "Monday, January 02, 2006"
time_format_default        = "January 2, 2006"

[drawio]
  enable = false

[plantuml]
  enable = false

[print]
  disable_toc = false

[markmap]
  enable = true

[mermaid]
  enable = true
  theme  = "dark"

  [mermaid.flowchart]
    diagramPadding = 20

[ui]
  breadcrumb_disable    = false
  sidebar_cache_limit   = 10
  sidebar_menu_compact  = true
  sidebar_menu_foldable = true

  [ui.readingtime]
    enable = true
