homePage = "/docs" # If this is removed then then the site will show a landing page.
show_metalinks = false
time_format_blog = "Monday, January 02, 2006"
time_format_default = "January 2, 2006"
offlineSearch = true
offlineSearchSummaryLength = 70
offlineSearchMaxResults = 10

[drawio]
enable = false

[plantuml]
enable = false

[print]
disable_toc = false

[markmap]
enable = true

[mermaid]
enable = true
theme = "dark"

[mermaid.flowchart]
diagramPadding = 20

[ui]
sidebar_menu_compact = true
sidebar_menu_foldable = false
sidebar_cache_limit = 10
breadcrumb_disable = false

[ui.readingtime]
enable = true
