version: "3.3"

services:

   site:
      image: defense-unicorns-hugo-theme/user-guide
      build:
         context: .
      ports:
         - "1313:1313"
      user: "${THEME_USER}"
      volumes:
         - /app/defense-unicorns-hugo-theme/userguide/node_modules
         - .:/app/defense-unicorns-hugo-theme
