# Theme config
#

# [services.googleAnalytics]
#     id = 'G-12345'

[permalinks]
    slides = "/slides/:title/"

[params]
    rss_sections = [
        "blog"
    ]
    time_format_blog = "Monday, January 02, 2006"
    time_format_default = "January 2, 2006"

[outputFormats.PRINT]
    baseName      = "index"
    isHTML        = true
    mediaType     = "text/html"
    path          = "_print"
    permalinkable = false

[module]
    [module.hugoVersion]
        extended = true
        min      = "0.120.0"

    [[module.mounts]]
        source = "assets"
        target = "assets"

    [[module.mounts]]
        source = "node_modules/bootstrap"
        target = "assets/vendor/bootstrap"

    [[module.mounts]]
        source = "node_modules/@fortawesome/fontawesome-free"
        target = "assets/vendor/Font-Awesome"

    [[module.mounts]]
        source = "i18n"
        target = "i18n"

    [[module.mounts]]
        source = "layouts"
        target = "layouts"

    [[module.mounts]]
        source = "static"
        target = "static"

    [[module.mounts]]
        source = "node_modules/@fortawesome/fontawesome-free/webfonts"
        target = "static/webfonts"

    [[module.mounts]]
        source = "../../node_modules/bootstrap"
        target = "assets/vendor/bootstrap"

    [[module.mounts]]
        source = "../../node_modules/@fortawesome/fontawesome-free"
        target = "assets/vendor/Font-Awesome"

    [[module.mounts]]
        source = "../../node_modules/@fortawesome/fontawesome-free/webfonts"
        target = "static/webfonts"
