# Hugo build configuration for Netlify
# (https://gohugo.io/hosting-and-deployment/hosting-on-netlify/#configure-hugo-version-in-netlify)

[build]
  command = "npm run docs-install && npm run build:preview"
  publish = "userguide/public"

  [build.environment]
    GO_VERSION   = "1.22.3"
    HUGO_VERSION = "0.126.3"

[context.production]
  command = "npm run docs-install && npm run build:production"
