description = "A Hugo theme for Defense Unicorns documentation sites"
features    = []
homepage    = "https://github.com/defenseunicorns/defense-unicorns-hugo-theme"
license     = "Apache 2.0"
licenselink = "https://github.com/defenseunicorns/defense-unicorns-hugo-theme/blob/main/LICENSE"
min_version = "0.110.0"
name        = "Defense Unicorns"
tags        = ["documentation", "multilingual", "customizable", "responsive", "docs"]

[author]
homepage = "https://github.com/defenseunicorns/defense-unicorns-hugo-theme"
name     = "Defense Unicorns"
