name = "Defense Unicorns"
license = "Apache 2.0"
licenselink = "https://github.com/defenseunicorns/defense-unicorns-hugo-theme/blob/main/LICENSE"
description = "A Hugo theme for Defense Unicorns documentation sites"
homepage = "https://github.com/defenseunicorns/defense-unicorns-hugo-theme"
tags = ["documentation", "multilingual", "customizable", "responsive", "docs"]
features = []
min_version = "0.110.0"

[author]
name = "Defense Unicorns"
homepage = "https://github.com/defenseunicorns/defense-unicorns-hugo-theme"
