baseURL         = "https://example.com"         #Change this to your URL
enableGitInfo   = true
enableRobotsTXT = true
theme           = "defense-unicorns-hugo-theme"

[languages.en]
  languageName = "English"

  [languages.en.params]
    description = "Theme for our documentation sites"
    title       = "Defense Unicorns Hugo Theme"

[params]
  # Merge theme defaults and allow overriding ../config/_default/params.toml
  _merge                 = 'deep'
  airgapped              = true
  archived_version       = false
  childPageSummaryLength = 100
  copyright              = "Defense Unicorns"
  github_project_repo    = "https://github.com/defenseunicorns/defense-unicorns-hugo-theme"
  github_repo            = "https://github.com/defenseunicorns/defense-unicorns-hugo-theme"
  github_subdir          = "userguide"
  no_list                = true
  url_latest_version     = "https://example.com"
  version                = "v1.0.0"
  version_menu           = "v1.0"

  # Examples of versioning.
  [[params.versions]]
    url     = "https://master.kubeflow.org"
    version = "v1.0 - Latest"

  [[params.versions]]
    url     = "https://v0-2.kubeflow.org"
    version = "v0.2"

  [[params.versions]]
    url     = "https://v0-3.kubeflow.org"
    version = "v0.3"

  [params.ui]
    navbar_logo = "img/uds-logo.svg" # The product logo on the navbar

  [[params.socialLinks]]
    desc = "Discussion and help from your fellow users"
    icon = "fa-brands fa-slack"
    name = "Community Slack"
    url  = "https://communityinviter.com/apps/kubernetes/community"

  [[params.socialLinks]]
    desc = "Defense Unicorns Twitter"
    icon = "fa-brands fa-twitter"
    name = "Twitter"
    url  = "https://twitter.com/DefenseUnicorns"

  [[params.socialLinks]]
    desc = ""
    icon = "fa-brands fa-github"
    name = "GitHub"
    url  = "https://github.com/defenseunicorns/defense-unicorns-hugo-theme"

[[module.mounts]]
  source = "content/en"
  target = "content"

###
# You can mount documents from other sources by mounting them here
# [[module.mounts]]
# source = "../docs"
# target = "content/docs"
###
[markup]
  _merge = 'shallow' # Use theme defaults

[outputs]
  _merge = 'shallow' # Use theme defaults

[imaging]
  _merge = 'shallow' # Use theme defaults

[taxonomies]
  _merge = 'shallow'
