enableGitInfo = true
enableRobotsTXT = true
baseURL = "https://example.com" #Change this to your URL
theme = "defense-unicorns-hugo-theme"

[languages.en]
languageName = "English"

[languages.en.params]
title = "Defense Unicorns Hugo Theme"
description = "Theme for our documentation sites"

[params]
_merge = 'deep' # Use theme defaults
copyright = "Defense Unicorns"
github_repo = "https://github.com/defenseunicorns/defense-unicorns-hugo-theme"
github_project_repo = "https://github.com/defenseunicorns/defense-unicorns-hugo-theme"
github_subdir = "userguide"
archived_version = false
version = "v1.0.0"
version_menu = "v1.0"
url_latest_version = "https://example.com"

# Examples of versioning.
[[params.versions]]
version = "v1.0 - Latest"
url = "https://master.kubeflow.org"

[[params.versions]]
version = "v0.2"
url = "https://v0-2.kubeflow.org"

[[params.versions]]
version = "v0.3"
url = "https://v0-3.kubeflow.org"

[params.ui]
navbar_logo = "img/uds-logo.svg" # The product logo on the navbar

[[params.socialLinks]]
name = "Community Slack"
url = "https://communityinviter.com/apps/kubernetes/community"
icon = "fa-brands fa-slack"
desc = "Discussion and help from your fellow users"

[[params.socialLinks]]
name = "Twitter"
url = "https://twitter.com/DefenseUnicorns"
icon = "fa-brands fa-twitter"
desc = "Defense Unicorns Twitter"

[[params.socialLinks]]
name = "GitHub"
url = "https://github.com/defenseunicorns/defense-unicorns-hugo-theme"
icon = "fa-brands fa-github"
desc = ""

[[module.mounts]]
source = "content/en"
target = "content"

###
# You can mount documents from other sources by mounting them here
# [[module.mounts]]
# source = "../docs"
# target = "content/docs"
###
[markup]
_merge = 'shallow' # Use theme defaults

[outputs]
_merge = 'shallow' # Use theme defaults

[imaging]
_merge = 'shallow' # Use theme defaults

[taxonomies]
_merge = 'shallow'
