
baseURL         = "https://example.com" #Change this to your URL
enableGitInfo   = true
enableRobotsTXT = true
# theme           = "defense-unicorns-hugo-theme"

[module]
  proxy = "direct"

  [[module.imports]]
    path = "github.com/defenseunicorns/defense-unicorns-hugo-theme"

  [[module.imports]]
    path = "github.com/defenseunicorns/defense-unicorns-hugo-theme/dependencies"

[languages.en]
  languageName = "English"

  [languages.en.params]
    description = "Theme for our documentation sites"
    title       = "Defense Unicorns Hugo Theme"

[params]
  # Merge theme defaults and allow overriding ../config/_default/params.toml
  _merge    = 'deep'
  airgapped = false              # Set to true to remove CDN dependencies
  copyright = "Defense Unicorns"

  github_project_repo = "https://github.com/defenseunicorns/defense-unicorns-hugo-theme"
  github_repo         = "https://github.com/defenseunicorns/defense-unicorns-hugo-theme"
  github_subdir       = "userguide"

  url_latest_version = "https://example.com"
  version            = "v1.0.0"
  version_menu       = "v1.0"

  [[params.socialLinks]]
    desc = "Discussion and help from your fellow users"
    icon = "fa-brands fa-slack"
    name = "Community Slack"
    url  = "https://communityinviter.com/apps/kubernetes/community"

  [[params.socialLinks]]
    desc = "Defense Unicorns Twitter"
    icon = "fa-brands fa-twitter"
    name = "Twitter"
    url  = "https://twitter.com/DefenseUnicorns"

  [[params.socialLinks]]
    desc = ""
    icon = "fa-brands fa-github"
    name = "GitHub"
    url  = "https://github.com/defenseunicorns/defense-unicorns-hugo-theme"

  [params.ui]
    navbar_logo = "img/uds-logo.svg" # The product logo on the navbar
    # show_nav_title = true

  ### Examples of versioning.
  [[params.versions]]
    url     = "https://master.kubeflow.org"
    version = "v1.0 - Latest"

  [[params.versions]]
    url     = "https://v0-2.kubeflow.org"
    version = "v0.2"

  [[params.versions]]
    url     = "https://v0-3.kubeflow.org"
    version = "v0.3"

[[module.mounts]]
  source = "content/en"
  target = "content"

  ###
  # You can mount documents from other sources by mounting them here
  # [[module.mounts]]
  # source = "../docs"
  # target = "content/docs"
  ###

  ###
  # For air-gapped, mount these dependencies
  # [[module.mounts]]
  #   source = "node_modules/redoc/bundles"
  #   target = "assets/js/redoc"

  # [[module.mounts]]
  #   source = "node_modules/mermaid/dist"
  #   target = "assets/js/mermaid"

  # [[module.mounts]]
  #   source = "node_modules/markmap-autoloader/dist"
  #   target = "assets/js/markmap-autoloader"

  # [[module.mounts]]
  #   source = "node_modules/jquery/dist"
  #   target = "assets/js/jquery"

  # [[module.mounts]]
  #   source = "node_modules/lunr"
  #   target = "assets/js/lunr"

  ### End air-gapped

[markup]
  _merge = 'shallow' # Use theme defaults

[outputs]
  _merge = 'shallow' # Use theme defaults

[imaging]
  _merge = 'shallow' # Use theme defaults

[taxonomies]
  _merge = 'shallow'
