baseURL = "https://example.com"
enableRobotsTXT = true
theme = "defense-unicorns-hugo-theme"
enableGitInfo = true
pygmentsCodeFences = true
pygmentsUseClasses = false
pygmentsUseClassic = false
pygmentsStyle = "tango"

[outputs]
home = ["HTML"]
page = ["HTML"]
section = ["HTML", "RSS", "print"]

[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "Smart"

[languages.en]
languageName = "English"

[languages.en.params]
title = "Defense Unicorns Hugo Theme"
description = "Theme for our documentation sites"

[markup.goldmark.parser.attribute]
block = true

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
style = "tango"

[params]
homePage = "/docs" # If this is removed then then the site will show a landing page.
show_metalinks = false
copyright = "Defense Unicorns"
github_repo = "https://github.com/defenseunicorns/defense-unicorns-hugo-theme"
github_project_repo = "https://github.com/defenseunicorns/defense-unicorns-hugo-theme"
github_subdir = "userguide"
time_format_blog = "Monday, January 02, 2006"
time_format_default = "January 2, 2006"
offlineSearch = true
offlineSearchSummaryLength = 70
offlineSearchMaxResults = 10
archived_version = false
version = "v1.0.0"
version_menu = "v1.0"
url_latest_version = "https://example.com"

# Add your release versions here that references the deployed release branch for that version.
[[params.versions]]
version = "v1.0 - Latest"
url = "https://master.kubeflow.org"

[[params.versions]]
version = "v0.2"
url = "https://v0-2.kubeflow.org"

[[params.versions]]
version = "v0.3"
url = "https://v0-3.kubeflow.org"

[params.ui]
navbar_logo = "img/uds-logo.svg" # The product logo on the navbar
sidebar_menu_compact = true
sidebar_menu_foldable = false
sidebar_cache_limit = 10
breadcrumb_disable = false

# navbar_search = true # If true, moves the searchbar to the navbar. Not recommended for mobile!
[params.ui.readingtime]
enable = true

[[params.socialLinks]]
name = "Community Slack"
url = "https://communityinviter.com/apps/kubernetes/community"
icon = "fa-brands fa-slack"
desc = "Discussion and help from your fellow users"

[[params.socialLinks]]
name = "Twitter"
url = "https://twitter.com/DefenseUnicorns"
icon = "fa-brands fa-twitter"
desc = "Defense Unicorns Twitter"

[[params.socialLinks]]
name = "GitHub"
url = "https://github.com/defenseunicorns/defense-unicorns-hugo-theme"
icon = "fa-brands fa-github"
desc = ""

[params.plantuml]
enable = true
theme = "default"
svg_image_url = "https://www.plantuml.com/plantuml/svg/"
svg = false

[params.print]
disable_toc = false

[params.markmap]
enable = true

[params.mermaid]
theme = "default"

[params.mermaid.flowchart]
diagramPadding = 20

[params.drawio]
enable = true

[taxonomies]
tag = "tags"
category = "categories"

[[module.mounts]]
source = "content/en"
target = "content"
