on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: Release

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Create release tag
        id: tag
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          command: manifest # use configs in release-please-config.json
