name: Release

on:
  workflow_run:
    workflows: ['Build and Test']
    branches: [main]
    types:
      - completed

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Create release tag
        id: tag
        uses: google-github-actions/release-please-action@v3
        with:
          command: manifest # use configs in release-please-config.json
